FORMAT: 1A
HOST: http://app.kartero.me

# kartero
Kartero is a *deliverability optimization* service.

# Group Profile
Profile-related resources

## Profile [/profile]
### Retrieve profile [GET]
+ Response 200 (application/hal+json)

        {
            "name":"name",
            "test":"test"
        }

# Group Mail
Mail-related resources

## Mail [/mail]
### Send mail [POST]
+ Request (application/json)

        { }

+ Response 200 (application/hal+json)

# Group List Management
## List [/lists]
### Create new list [POST]
+ Request (application/json)

        {}

+ Response 201 (application/hal+json)

## List [/lists/{id}]
### Retrieve a list [GET]
+ Response 200 (application/hal+json)

### Delete a list [DELETE]
+ Response 204

# Group Event Management
## 

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
